"""empty message

Revision ID: 17c23283c89d
Revises: 3f9ce1f502d9
Create Date: 2021-09-12 18:32:01.463126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c23283c89d'
down_revision = '3f9ce1f502d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SQL__pastes',
    sa.Column('identifier', sa.String(length=5), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('paste_text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('identifier'),
    sa.UniqueConstraint('identifier')
    )
    op.drop_table('pastes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastes',
    sa.Column('identifier', sa.VARCHAR(length=5), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('paste_text', sa.TEXT(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('identifier'),
    sa.UniqueConstraint('identifier')
    )
    op.drop_table('SQL__pastes')
    # ### end Alembic commands ###
